#:schema https://raw.githubusercontent.com/lapce/lapce/master/extra/schemas/color-theme.json
[color-theme]
name = "Catppuccin Macchiato"

[ui]
font-family = ""
font-size = 13
header-height = 35
status-height = 25
tab-min-width = 100
activity-width = 50
scroll-width = 10
drop-shadow-width = 0

[color-theme.base]

black = "#494d64"
blue = "#8aadf4"
cyan = "#8bd5ca"
green = "#a6da95"
magenta = "#f5bde6"
orange = "#f5a97f"
purple = "#c6a0f6"
red = "#ed8796"
white = "#b8c0e0"
yellow = "#eed49f"

[color-theme.syntax]
"comment" = "#6e738d"
"constant" = "#f5a97f"
"type" = "$yellow"
"typeAlias" = "$yellow"
"number" = "$yellow"
"enum" = "$yellow"
"struct" = "$yellow"
"structure" = "$yellow"
"interface" = "$yellow"
"attribute" = "$yellow"
"constructor" = "#7dc4e4"

"function" = "$blue"
"method" = "$blue"
"function.method" = "#c6a0f6"

"keyword" = "#c6a0f6"
"selfKeyword" = "$purple"

"field" = "$red"
"property" = "$red"
"enumMember" = "$red"
"enum-member" = "$red"

"string" = "$green"
"string.escape" = "$cyan"

"type.builtin" = "$red"
"builtinType" = "$red"
"escape" = "#8bd5ca"
"embedded" = "#8bd5ca"

"punctuation.delimiter" = "#939ab7"
"text.title" = "$orange"
"text.uri" = "$cyan"
"text.reference" = "$yellow"
"variable" = "$red"
"variable.other.member" = "$green"
"tag" = "#c6a0f6"


[color-theme.ui]
"lapce.error" = "$red"
"lapce.warn" = "$yellow"
"lapce.dropdown_shadow" = "#5b6078"
"lapce.border" = "#5b6078"
"lapce.scroll_bar" = "#363a4f"

"lapce.button.primary.background" = "#c6a0f6"
"lapce.button.primary.foreground" = "#24273a"

# tab
"lapce.tab.active.background" = "#24273a"
"lapce.tab.active.foreground" = "#c6a0f6"
"lapce.tab.active.underline" = "#c6a0f6"

"lapce.tab.inactive.background" = "#24273a"
"lapce.tab.inactive.foreground" = "#a5adcb"
"lapce.tab.inactive.underline" = "#a5adcb"

"lapce.tab.separator" = "#181926"

"lapce.icon.active" = "$white"
"lapce.icon.inactive" = "#585c70"

"lapce.remote.icon" = "$purple"
"lapce.remote.local" = "#181926"
"lapce.remote.connected" = "#50A14F"
"lapce.remote.connecting" = "#C18401"
"lapce.remote.disconnected" = "#E45649"

"lapce.plugin.name" = "#DDDDDD"
"lapce.plugin.description" = "$white"
"lapce.plugin.author" = "#B0B0B0"


"editor.background" = "#24273a"
"editor.foreground" = "#cad3f5"
"editor.dim" = "#8087a2"
"editor.focus" = "#CCCCCC"
"editor.caret" = "#8bd5ca"
"editor.selection" = "#5b6078"
"editor.current_line" = "#0b0b0f"
"editor.link" = "#f4dbd6"
"editor.visible_whitespace" = "$grey"
"editor.indent_guide" = "$grey"
"editor.drag_drop_background" = "#7dc4e455"
"editor.drag_drop_tab_background" = "#0b0e1455"
"editor.sticky_header_background" = "$black"

"inlay_hint.foreground" = "#494d64"
"inlay_hint.background" = "#1e2030"

"source_control.added" = "#a6da9532"
"source_control.removed" = "#ee99a032"
"source_control.modified" = "#8aadf432"

"palette.background" = "#24273a"
"palette.current" = "#181926"

"completion.background" = "#24273a"
"completion.current" = "#5b6078"

"hover.background" = "#24273a"

"activity.background" = "#1e2030"
"activity.current" = "#181926"


"debug.breakpoint" = "$red"
"debug.breakpoint.hover" = "$grey"

"panel.background" = "#1e2030"
"panel.foreground" = "#cad3f5"
"panel.foreground.dim" = "#8b9fe9"
"panel.current.background" = "#181926"
"panel.current.foreground" = "#cad3f5"
"panel.current.foreground.dim" = "#8b9fe9"
"panel.hovered.background" = "#181926"
"panel.hovered.active.background" = "#15171f"
"panel.hovered.foreground" = "#cad3f5"
"panel.hovered.foreground.dim" = "#8b9fe9"

"status.background" = "#1e2030"
"status.foreground" = "$white"
"status.modal.normal.background" = "$blue"
"status.modal.normal.foreground" = "$black"
"status.modal.insert.background" = "$red"
"status.modal.insert.foreground" = "$black"
"status.modal.visual.background" = "$yellow"
"status.modal.visual.foreground" = "$black"
"status.modal.terminal.background" = "$purple"
"status.modal.terminal.foreground" = "$black"


"markdown.blockquote" = "#a5adcb"

"terminal.cursor" = "#f4dbd6"
"terminal.foreground" = "#cad3f5"
"terminal.background" = "#24273a"
"terminal.white" = "#b8c0e0"
"terminal.black" = "#494d64"
"terminal.red" = "$red"
"terminal.blue" = "$blue"
"terminal.green" = "$green"
"terminal.yellow" = "$yellow"
"terminal.cyan" = "#8bd5ca"
"terminal.magenta" = "#f5bde6"
"terminal.bright_white" = "#a5adcb"
"terminal.bright_red" = "$red"
"terminal.bright_blue" = "$blue"
"terminal.bright_green" = "$green"
"terminal.bright_yellow" = "$yellow"
"terminal.bright_cyan" = "#8bd5ca"
"terminal.bright_magenta" = "#f5bde6"
"terminal.bright_black" = "#5b6078"
