#:schema https://raw.githubusercontent.com/lapce/lapce/master/extra/schemas/color-theme.json
[color-theme]
name = "Catppuccin Frappé"

[ui]
font-family = ""
font-size = 13
header-height = 35
status-height = 25
tab-min-width = 100
activity-width = 50
scroll-width = 10
drop-shadow-width = 0

[color-theme.base]

black = "#51576d"
blue = "#8caaee"
cyan = "#81c8be"
green = "#a6d189"
magenta = "#f4b8e4"
orange = "#ef9f76"
purple = "#ca9ee6"
red = "#e78284"
white = "#b5bfe2"
yellow = "#e5c890"

[color-theme.syntax]
"comment" = "#949cbb"
"constant" = "#ef9f76"
"type" = "$yellow"
"typeAlias" = "$yellow"
"number" = "$peach"
"enum" = "$yellow"
"struct" = "$yellow"
"structure" = "$yellow"
"interface" = "$yellow"
"attribute" = "$yellow"
"constructor" = "#85c1dc"

"function" = "$blue"
"method" = "$blue"
"function.method" = "#ca9ee6"

"keyword" = "#ca9ee6"
"selfKeyword" = "$purple"

"field" = "$blue"
"property" = "$blue"
"enumMember" = "$teal"
"enum-member" = "$teal"

"string" = "$green"
"string.escape" = "$pink"

"type.builtin" = "$red"
"builtinType" = "$red"
"escape" = "#f4b8e4"
"embedded" = "#81c8be"

"punctuation.delimiter" = "#949cbb"
"text.title" = "$orange"
"text.uri" = "$blue"
"text.reference" = "$yellow"
"variable" = "$text"
"variable.other.member" = "$blue"
"tag" = "#8caaee"


[color-theme.ui]
"lapce.error" = "$red"
"lapce.warn" = "$yellow"
"lapce.dropdown_shadow" = "#626880"
"lapce.border" = "#626880"
"lapce.scroll_bar" = "#414559"

"lapce.button.primary.background" = "#ca9ee6"
"lapce.button.primary.foreground" = "#303446"

# tab
"lapce.tab.active.background" = "#303446"
"lapce.tab.active.foreground" = "#ca9ee6"
"lapce.tab.active.underline" = "#ca9ee6"

"lapce.tab.inactive.background" = "#303446"
"lapce.tab.inactive.foreground" = "#a5adce"
"lapce.tab.inactive.underline" = "#a5adce"

"lapce.tab.separator" = "#232634"

"lapce.icon.active" = "$white"
"lapce.icon.inactive" = "#5c6178"

"lapce.remote.icon" = "$purple"
"lapce.remote.local" = "#232634"
"lapce.remote.connected" = "#50A14F"
"lapce.remote.connecting" = "#C18401"
"lapce.remote.disconnected" = "#E45649"

"lapce.plugin.name" = "#DDDDDD"
"lapce.plugin.description" = "$white"
"lapce.plugin.author" = "#B0B0B0"


"editor.background" = "#303446"
"editor.foreground" = "#c6d0f5"
"editor.dim" = "#838ba7"
"editor.focus" = "#CCCCCC"
"editor.caret" = "#81c8be"
"editor.selection" = "#626880"
"editor.current_line" = "#0b0c0f"
"editor.link" = "#f2d5cf"
"editor.visible_whitespace" = "$grey"
"editor.indent_guide" = "$grey"
"editor.drag_drop_background" = "#85c1dc55"
"editor.drag_drop_tab_background" = "#0b0e1455"
"editor.sticky_header_background" = "$black"

"inlay_hint.foreground" = "#51576d"
"inlay_hint.background" = "#292c3c"

"source_control.added" = "#a6d18932"
"source_control.removed" = "#ea999c32"
"source_control.modified" = "#8caaee32"

"palette.background" = "#303446"
"palette.current" = "#232634"

"completion.background" = "#303446"
"completion.current" = "#626880"

"hover.background" = "#303446"

"activity.background" = "#292c3c"
"activity.current" = "#232634"


"debug.breakpoint" = "$red"
"debug.breakpoint.hover" = "$grey"

"panel.background" = "#292c3c"
"panel.foreground" = "#c6d0f5"
"panel.foreground.dim" = "#869cea"
"panel.current.background" = "#232634"
"panel.current.foreground" = "#c6d0f5"
"panel.current.foreground.dim" = "#869cea"
"panel.hovered.background" = "#232634"
"panel.hovered.active.background" = "#16171e"
"panel.hovered.foreground" = "#c6d0f5"
"panel.hovered.foreground.dim" = "#869cea"

"status.background" = "#292c3c"
"status.foreground" = "$white"
"status.modal.normal.background" = "$blue"
"status.modal.normal.foreground" = "$black"
"status.modal.insert.background" = "$red"
"status.modal.insert.foreground" = "$black"
"status.modal.visual.background" = "$yellow"
"status.modal.visual.foreground" = "$black"
"status.modal.terminal.background" = "$purple"
"status.modal.terminal.foreground" = "$black"


"markdown.blockquote" = "#a5adce"

"terminal.cursor" = "#f2d5cf"
"terminal.foreground" = "#c6d0f5"
"terminal.background" = "#303446"
"terminal.white" = "#b5bfe2"
"terminal.black" = "#51576d"
"terminal.red" = "$red"
"terminal.blue" = "$blue"
"terminal.green" = "$green"
"terminal.yellow" = "$yellow"
"terminal.cyan" = "#81c8be"
"terminal.magenta" = "#f4b8e4"
"terminal.bright_white" = "#a5adce"
"terminal.bright_red" = "$red"
"terminal.bright_blue" = "$blue"
"terminal.bright_green" = "$green"
"terminal.bright_yellow" = "$yellow"
"terminal.bright_cyan" = "#81c8be"
"terminal.bright_magenta" = "#f4b8e4"
"terminal.bright_black" = "#626880"
